### ISSUE TITLE
Add tabbed component that switches between mainnet/testnet/localnet

### ISSUE THREAD

**Issue by a1300** [GNYIO/gny-docs#89]
First ticket  #31  must be finished

With the [vuepress-plugin-tabs](https://github.com/superbiger/vuepress-plugin-tabs) vuepress extension we can show a **tabbed** component for `mainnet/testnet/localnet`. The [docs.gny.io](docs.gny.io) site is not so different for `localnet/mainnet`. I think **one** site for all networks (`mainnet/testnet/localnet`) is enough. We don't need `testnet.docs.gny.io` and `mainnet.docs.gny.io`

![image](https://user-images.githubusercontent.com/11912239/104835880-e3d47100-58a9-11eb-9af2-00c011f462a7.png)

# TODO
- Add tabbed components for
  - [x] All references to testnet node (`https://testnet.gny.io/` or `45.76.215.117`)
  - [x] All `--network / GNY_NETWORK` usages
  - [x] All `docker-compose.yml` examples
  - [x] Where it is needed else

**Comment by a1300** [comment]
Closed with PR: #100
